aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\desktop\Dessins\Grand nuage, fusain sur papier 2, 104x133cm 2021.webp" s3://morgan-site-pictures-by-device-type/desktop/Dessins/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\desktop\Dessins\Nuages de nuit, fusain sur papier, 104x133cm, 2021.webp" s3://morgan-site-pictures-by-device-type/desktop/Dessins/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\desktop\Peintures\Ciel sévillan, huile sur toile, 54x65cm, 2020.webp" s3://morgan-site-pictures-by-device-type/desktop/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\desktop\Peintures\Ciel, huile sur toile, 33x41cm, 2020.webp" s3://morgan-site-pictures-by-device-type/desktop/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\desktop\Peintures\Crâne d'amabié, acrylique sur toile, 130x195cm, 2019.webp" s3://morgan-site-pictures-by-device-type/desktop/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\desktop\Peintures\Grand choral, acrylique sur toile, 149x230cm, 2020.webp" s3://morgan-site-pictures-by-device-type/desktop/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\desktop\Peintures\Grand nuage de nuit, huile sur toile, 156x195cm, 2020.webp" s3://morgan-site-pictures-by-device-type/desktop/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\desktop\Peintures\Gros ciel, huile sur toile,89x116cm, 2020.webp" s3://morgan-site-pictures-by-device-type/desktop/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\desktop\Peintures\L'ombre cramoisie, acrylique sur toile, 114x195cm, 2019.webp" s3://morgan-site-pictures-by-device-type/desktop/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\desktop\Peintures\Nocturne, huile sur toile, 22x16cm, 2020.webp" s3://morgan-site-pictures-by-device-type/desktop/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\desktop\Peintures\Nuage, huile sur toile, 30x30cm, 2020.webp" s3://morgan-site-pictures-by-device-type/desktop/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\desktop\Peintures\Nuage, huile sur toile,20x29,5cm, 2022 2022.webp" s3://morgan-site-pictures-by-device-type/desktop/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\desktop\Peintures\Nuit bleue, huile sur toile, 25x30cm 2022.webp" s3://morgan-site-pictures-by-device-type/desktop/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\desktop\Peintures\Nuit bleue, huile sur toile, 60x73cm, 2022.webp" s3://morgan-site-pictures-by-device-type/desktop/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\desktop\Peintures\Nuit sévillane, 50x100cm, 2020.webp" s3://morgan-site-pictures-by-device-type/desktop/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\desktop\Peintures\Nuit, huile sur toile, 54x65cm, 2022.webp" s3://morgan-site-pictures-by-device-type/desktop/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\desktop\Peintures\Rouge, huile sur toile, 16x22cm, 2019.webp" s3://morgan-site-pictures-by-device-type/desktop/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Dessins\Ciel, fusain sur papier, 47x67cm, 2021.webp" s3://morgan-site-pictures-by-device-type/mobile/Dessins/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Dessins\Grand nuage, fusain sur papier 2, 104x133cm 2021.webp" s3://morgan-site-pictures-by-device-type/mobile/Dessins/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Dessins\Nuages de nuit, fusain sur papier, 104x133cm, 2021.webp" s3://morgan-site-pictures-by-device-type/mobile/Dessins/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Peintures\Ciel sévillan, huile sur toile, 54x65cm, 2020.webp" s3://morgan-site-pictures-by-device-type/mobile/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Peintures\Ciel, huile sur toile, 33x41cm, 2020.webp" s3://morgan-site-pictures-by-device-type/mobile/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Peintures\Crâne d'amabié, acrylique sur toile, 130x195cm, 2019.webp" s3://morgan-site-pictures-by-device-type/mobile/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Peintures\Grand choral, acrylique sur toile, 149x230cm, 2020.webp" s3://morgan-site-pictures-by-device-type/mobile/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Peintures\Grand nuage de nuit, huile sur toile, 156x195cm, 2020.webp" s3://morgan-site-pictures-by-device-type/mobile/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Peintures\Gros ciel, huile sur toile,89x116cm, 2020.webp" s3://morgan-site-pictures-by-device-type/mobile/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Peintures\L'ombre cramoisie, acrylique sur toile, 114x195cm, 2019.webp" s3://morgan-site-pictures-by-device-type/mobile/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Peintures\Nocturne, huile sur toile, 22x16cm, 2020.webp" s3://morgan-site-pictures-by-device-type/mobile/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Peintures\Nuage, huile sur toile, 30x30cm, 2020.webp" s3://morgan-site-pictures-by-device-type/mobile/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Peintures\Nuage, huile sur toile,20x29,5cm, 2022 2022.webp" s3://morgan-site-pictures-by-device-type/mobile/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Peintures\Nuit bleue, huile sur toile, 25x30cm 2022.webp" s3://morgan-site-pictures-by-device-type/mobile/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Peintures\Nuit bleue, huile sur toile, 60x73cm, 2022.webp" s3://morgan-site-pictures-by-device-type/mobile/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Peintures\Nuit sévillane, 50x100cm, 2020.webp" s3://morgan-site-pictures-by-device-type/mobile/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Peintures\Nuit, huile sur toile, 54x65cm, 2022.webp" s3://morgan-site-pictures-by-device-type/mobile/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\mobile\Peintures\Rouge, huile sur toile, 16x22cm, 2019.webp" s3://morgan-site-pictures-by-device-type/mobile/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Dessins\Ciel, fusain sur papier, 47x67cm, 2021.webp" s3://morgan-site-pictures-by-device-type/tablet/Dessins/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Dessins\Grand nuage, fusain sur papier 2, 104x133cm 2021.webp" s3://morgan-site-pictures-by-device-type/tablet/Dessins/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Dessins\Nuages de nuit, fusain sur papier, 104x133cm, 2021.webp" s3://morgan-site-pictures-by-device-type/tablet/Dessins/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Peintures\Ciel sévillan, huile sur toile, 54x65cm, 2020.webp" s3://morgan-site-pictures-by-device-type/tablet/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Peintures\Ciel, huile sur toile, 33x41cm, 2020.webp" s3://morgan-site-pictures-by-device-type/tablet/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Peintures\Crâne d'amabié, acrylique sur toile, 130x195cm, 2019.webp" s3://morgan-site-pictures-by-device-type/tablet/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Peintures\Grand choral, acrylique sur toile, 149x230cm, 2020.webp" s3://morgan-site-pictures-by-device-type/tablet/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Peintures\Grand nuage de nuit, huile sur toile, 156x195cm, 2020.webp" s3://morgan-site-pictures-by-device-type/tablet/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Peintures\Gros ciel, huile sur toile,89x116cm, 2020.webp" s3://morgan-site-pictures-by-device-type/tablet/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Peintures\L'ombre cramoisie, acrylique sur toile, 114x195cm, 2019.webp" s3://morgan-site-pictures-by-device-type/tablet/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Peintures\Nocturne, huile sur toile, 22x16cm, 2020.webp" s3://morgan-site-pictures-by-device-type/tablet/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Peintures\Nuage, huile sur toile, 30x30cm, 2020.webp" s3://morgan-site-pictures-by-device-type/tablet/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Peintures\Nuage, huile sur toile,20x29,5cm, 2022 2022.webp" s3://morgan-site-pictures-by-device-type/tablet/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Peintures\Nuit bleue, huile sur toile, 25x30cm 2022.webp" s3://morgan-site-pictures-by-device-type/tablet/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Peintures\Nuit bleue, huile sur toile, 60x73cm, 2022.webp" s3://morgan-site-pictures-by-device-type/tablet/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Peintures\Nuit sévillane, 50x100cm, 2020.webp" s3://morgan-site-pictures-by-device-type/tablet/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Peintures\Nuit, huile sur toile, 54x65cm, 2022.webp" s3://morgan-site-pictures-by-device-type/tablet/Peintures/
aws s3 cp "C:\Users\deschaseauxr\Documents\Morgan-site\Morgan-site\pictures-by-device-type\tablet\Peintures\Rouge, huile sur toile, 16x22cm, 2019.webp" s3://morgan-site-pictures-by-device-type/tablet/Peintures/